name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update apt...
        run: sudo apt update
      - name: Setup OpenCV
        run: sudo apt install libopencv-dev
      - name: Setup OpenCL
        run: sudo apt install ocl-icd-* opencl-headers
      - name: Make Tpx3 Dosi Lib
        run: cmake -S Tpx3Dosi -B build
      - name: Build OCL DaMa
        run: cmake --build build --config Release
