name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Init submodules
        run: git submodule update --init
      - name: Update apt...
        run: sudo apt update
      - name: Setup OpenCV
        run: sudo apt install libopencv-dev
      - name: Setup OpenCL
        run: sudo apt install ocl-icd-* opencl-headers
      - name: Make OCL DaMa
        run: cmake -S . -B build
      - name: Build OCL DaMa
        run: cmake --build build --config Release
